### ISSUE TITLE
Tracking pixel in email and MMS message

### ISSUE THREAD

**Issue by shaunc869** [resulto/pytracking#3]
Hi!

First let me say thanks a ton for this library it's an awesome thing, I was wondering could you give me sample code and/or a walk through of how to use this to generate a real time 1x1 pixel that when loaded allows me to capture an open event on an email and/or an MMS message? Thanks!

**Comment by bartdag** [comment]
Hi, which web framework are you using?

I will assume that you are already sending an HTML message as part of your application (open tracking pixel does not work with plain text message). There are thus two major steps: adding the image tag in your email, and serving the pixel with a web server.

# Step 1 - Adding a ``<img>`` tag

First, you need to add a ``<img src>`` tag, usually at the bottom of the email if it isn't too long. If the email is likely to be cut by the email reader because it is lengthy, you should put the pixel at the top of the ``<body>`` tag, but this may mess with your layout.

The src attribute will be a link generated by [pytracking.get_open_tracking_url](https://github.com/resulto-admin/pytracking#get-open-tracking-link). You must make sure that you are able to receive requests at the path specified in the parameters. In the example, a webserver is able to receive GET requests at ``https://trackingdomain.com/path/<anything here>``

Is this part ok?

# Step 2 - Serving the pixel with a web server

The second part is actually serving the pixel when the user opens the email.

If you use Django, we already offer a View class. Otherwise, you need to do two things:

1. Decode the URL and record the open (e.g., by writing something to a log file or a database).
2. Serve the Pixel with the correct MIME type.

About step 1, you need to call [pytracking.get_open_tracking_result](https://github.com/resulto-admin/pytracking#get-open-tracking-data-from-url). This will give you all the metadata you encoded with your link such as customer id.

About step 2, you can serve your own 1x1 pixel saved on disk, or you can use pytracking which already has the pixel in memory by calling [pytracking.get_open_tracking_pixel](https://github.com/resulto-admin/pytracking#get-a-1x1-transparent-png-pixel)

# Additional tips

If you use Django, please [look at this section](https://github.com/resulto-admin/pytracking#using-pytracking-with-django) for more information about the View class we provide to serve an open and click tracking link.

If you do not want to add the ``<img>`` src manually, you can use [pytracking.html.adapt_html](https://github.com/resulto-admin/pytracking#modifying-html-emails-to-add-tracking-links) which accepts your HTML as a string and outputs the same HTML with all links converted to click tracking links (optional) and adds an ``<img>`` tag for open tracking at the end of the email.
