### ISSUE TITLE
Is there any way to have this work with Python 2.7?

### ISSUE THREAD

**Issue by capcom-r** [resulto/pytracking#5]
I'd really love to use this library but I'm on 2.7. Any way I can get this to work?

Thanks!

**Comment by bartdag** [comment]
You could submit a pull request. The steps would be:

1. Copy the python six library in the project (I usually prefer to copy six instead of adding another dependency for this particular library).
2. Use six wherever it makes sense (mostly when dealing with strings)
3. Modify tox.ini to include py27 (all variants)
4. Modify circle.yml to include missing libraries (I believe only python-dev is missing). I think the image we are using has python2.7 installed by default so tox should run as is.

**Comment by capcom-r** [comment]
@bartdag Thanks for the guidance! I couldn't wait much longer so I just stayed up and wrote a smaller custom package myself before I saw this. I would like to submit a pull request here though, but then again I should upgrade to 3.x at some point too ... I'll try to come back to this soon. Thanks a lot for replying.
